name: QC-Core
version: 1.0
main: pl.qc.core.QC
api-version: 1.19
authors: [Rajman03]
description: Systemowy plugin serwerowy
depend: [ProtocolLib]

commands:
  qc:
    description: System command
    usage: /qc <subcmd>

